full_rebuild: true

title: Stuart's life
description: I have life. This is my journey to not let it slip through my fingers.
url: "http://stuart.life/"

markdown: kramdown
highlighter: null

destination: ../www
